### ISSUE TITLE
it's time for new release?

### ISSUE THREAD

**Issue by schoekek** [puppetlabs/puppetlabs-lvm#276]
since last tag was long time....

**Comment by fragfutter** [comment]
also add support for puppet > 7 and stdlib > 7 in metadata.json

**Comment by kbucheli** [comment]
The dependencies have been updated a while ago (https://github.com/puppetlabs/puppetlabs-lvm/commit/edd206c7b5c39d323942f9f28e111312a62815f5) so a release would indeed be handy.
