### ISSUE TITLE
Update for stdlib 9.x.x

### ISSUE THREAD

**Issue by jcpunk** [puppetlabs/puppetlabs-lvm#285]
## Use Case
With stdlib 9 out, this module should be compatible with that library.

## Describe the Solution You Would Like
Test with stdlib 9 and find a way to ensure compatibility for 8.x and 9.x

## Describe Alternatives You've Considered
Dropping this module

**Comment by jordanbreen28** [comment]
Hey @jcpunk - we are in the process of rolling the puppetlabs/stdlib bump to all our supported modules and this will be completed by COB tomorrow.
