### ISSUE TITLE
volume.pp extents resource type unknown

### ISSUE THREAD

**Issue by jcwarp** [puppetlabs/puppetlabs-lvm#290]
## A clear and concise description of what the bug is.

resource type for extents in parameter list for volume class is "Optional[Variant[String[1], Integert]]"
This causes an error:
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Resource type not found: Integert (file: /etc/puppetlabs/code/environments/production/modules/lvm/manifests/volume.pp, line: 70, column: 31) on node ...

Source:	Puppet

## Expected Behavior
puppet agent runs not to fail catalog compilation

## Steps to Reproduce
1. Add an LVM definition to your node catalog, with a volume
2. Try to compile a catalog

## Environment
 - Version: 6.14.0
 - Platform: Centos 7

## Additional Context
This looks like a typo, so I am surprised that the puppet parser passes this.
Interestingly, the parser does error out on the expand plan, but this looks OK to me ¯\_(ツ)_/¯
Error: Could not parse for environment production: Syntax error at 'server' (file: /etc/puppetlabs/code/environments/production/modules/lvm/plans/expand.pp, line: 16, column: 17)

**Comment by jordanbreen28** [comment]
Great spot @jcwarp! Strange this wasn't picked up like you say.. I'm working to get v2.0.1 released to the forge with a bugfix in place for this within the next hour.
