### ISSUE TITLE
Facts lvm_vg_* unavailable

### ISSUE THREAD

**Issue by rtib** [puppetlabs/puppetlabs-lvm#298]
## Describe the Bug
Facts `lvm_vg_*` and `lvm_vg_*_pvs` aren't resolved since v2.0.0 release.

## Expected Behavior
As those facts where not declared deprecated neither removed from the code, they are expected to be available.

## Steps to Reproduce
1. Run `sudo puppet facts | grep lvm_vg` on a node having LVM volume groups configured with module version 2.0.x and earlier.

## Environment
 - Puppet agent version 7.24.0 (others may also affected)
 - Platform Debian 11 (other may also affected)

## Additional Context
With commit https://github.com/puppetlabs/puppetlabs-lvm/commit/8e1e8eb1718f31a75d9edf79b123c74d61364e55 the setcode blocks of the affected facts [here](https://github.com/puppetlabs/puppetlabs-lvm/blob/v2.0.0/lib/facter/lvm_support.rb#L30..L32) have been moved into the `setcode` block above. I assume, such an encapsulation of `setcode` blocks is not supported with Facter.

**Comment by cruelsmith** [comment]
As @rtib also pointed out via slack the newer structured facts `logical_volumes`, `physical_volumes` and `volume_groups` are missing its relations to each other.
That should be also fixed by adding `pv_name`, `vg_name`, `lv_full_name` to the structured facts so it allows cross referencing.
